spring.application.name=instagram-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/instagram_tracker
spring.datasource.username=postgres
spring.datasource.password=instagram26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8080
